name: Cypress BAS End 2 End Regression Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
<<<<<<< HEAD
        
=======
>>>>>>> 51d60090a0a3b1e8e210aa7dc4bbeff53f33c25a
